<?php

return [
    'categories' => [
        ['id' => 'psicologia-clinica', 'name' => 'Psicologia Clinica'],
        ['id' => 'neurociencias', 'name' => 'Neurociencias'],
        ['id' => 'psicologia-infantil', 'name' => 'Psicologia Infantil'],
        ['id' => 'terapia-de-pareja', 'name' => 'Terapia de Pareja'],
    ],
    'courses' => [
        [
            'id' => 'tcc-avanzada',
            'title' => 'Terapia Cognitivo Conductual Avanzada',
            'type' => 'Curso',
            'instructor' => 'Dra. Carolina Mendez',
            'category' => 'psicologia-clinica',
            'startDate' => '15/04/2026',
            'originalPrice' => 450000,
            'discountPrice' => 349990,
            'modality' => 'En Vivo',
            'image' => 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21?w=600&h=400&fit=crop',
            'description' => 'Profundiza en las tecnicas avanzadas de la TCC aplicadas a trastornos de ansiedad y depresion.',
            'rating' => 4.9,
            'reviewCount' => 127,
            'status' => 'En progreso',
            'discountEndsIn' => ['days' => 2, 'hours' => 14, 'minutes' => 30, 'seconds' => 0],
            'tooltipText' => 'Sesiones 100% en vivo, si no puedes asistir, puedes revisar posteriormente la grabacion en tu aula virtual.',
        ],
        [
            'id' => 'intervencion-crisis',
            'title' => 'Intervencion en Crisis y Primeros Auxilios Psicologicos',
            'type' => 'Curso',
            'instructor' => 'Dr. Felipe Rojas',
            'category' => 'psicologia-clinica',
            'startDate' => '22/04/2026',
            'originalPrice' => 380000,
            'discountPrice' => 380000,
            'modality' => 'Online',
            'image' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop',
            'description' => 'Aprende protocolos de intervencion inmediata en situaciones de crisis psicologica.',
            'rating' => 4.8,
            'reviewCount' => 89,
            'status' => 'Proximo a iniciar',
            'discountEndsIn' => ['days' => 0, 'hours' => 0, 'minutes' => 0, 'seconds' => 0],
            'tooltipText' => 'Curso 100% online con material disponible en tu aula virtual por 8 semanas.',
        ],
        [
            'id' => 'evaluacion-psicodiagnostica',
            'title' => 'Evaluacion Psicodiagnostica en Adultos',
            'type' => 'Diplomado',
            'instructor' => 'Dra. Valentina Soto',
            'category' => 'psicologia-clinica',
            'startDate' => '05/05/2026',
            'originalPrice' => 520000,
            'discountPrice' => 520000,
            'modality' => 'Presencial',
            'image' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&h=400&fit=crop',
            'description' => 'Domina las herramientas de evaluacion psicologica mas utilizadas en el contexto clinico adulto.',
            'rating' => 5.0,
            'reviewCount' => 64,
            'status' => 'Proximo a iniciar',
            'discountEndsIn' => ['days' => 0, 'hours' => 0, 'minutes' => 0, 'seconds' => 0],
            'tooltipText' => 'Sesiones presenciales en sede Santiago. Incluye material de apoyo digital.',
        ],
        [
            'id' => 'neuropsicologia-aprendizaje',
            'title' => 'Neuropsicologia del Aprendizaje',
            'type' => 'Curso',
            'instructor' => 'Dr. Andres Villanueva',
            'category' => 'neurociencias',
            'startDate' => '10/05/2026',
            'originalPrice' => 400000,
            'discountPrice' => 400000,
            'modality' => 'En Vivo',
            'image' => 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=600&h=400&fit=crop',
            'description' => 'Explora las bases neuropsicologicas del aprendizaje y sus implicancias en la practica educativa.',
            'rating' => 4.7,
            'reviewCount' => 95,
            'status' => 'En progreso',
            'discountEndsIn' => ['days' => 0, 'hours' => 0, 'minutes' => 0, 'seconds' => 0],
            'tooltipText' => 'Sesiones 100% en vivo, si no puedes asistir, puedes revisar posteriormente la grabacion en tu aula virtual.',
        ],
        [
            'id' => 'bases-neurocientificas',
            'title' => 'Bases Neurocientificas de la Conducta',
            'type' => 'Curso',
            'instructor' => 'Dra. Isabel Fuentes',
            'category' => 'neurociencias',
            'startDate' => '18/05/2026',
            'originalPrice' => 360000,
            'discountPrice' => 360000,
            'modality' => 'Online',
            'image' => 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600&h=400&fit=crop',
            'description' => 'Comprende como el cerebro regula la conducta humana desde una perspectiva neurocientifica actual.',
            'rating' => 4.6,
            'reviewCount' => 73,
            'status' => 'En progreso',
            'discountEndsIn' => ['days' => 0, 'hours' => 0, 'minutes' => 0, 'seconds' => 0],
            'tooltipText' => 'Curso 100% online con material disponible en tu aula virtual por 8 semanas.',
        ],
        [
            'id' => 'evaluacion-infantojuvenil',
            'title' => 'Evaluacion Psicologica Infantojuvenil',
            'type' => 'Diplomado',
            'instructor' => 'Dra. Marcela Gonzalez',
            'category' => 'psicologia-infantil',
            'startDate' => '25/05/2026',
            'originalPrice' => 480000,
            'discountPrice' => 389990,
            'modality' => 'En Vivo',
            'image' => 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&h=400&fit=crop',
            'description' => 'Aprende a aplicar e interpretar las principales baterias de evaluacion psicologica infantojuvenil.',
            'rating' => 4.9,
            'reviewCount' => 112,
            'status' => 'En progreso',
            'discountEndsIn' => ['days' => 2, 'hours' => 3, 'minutes' => 50, 'seconds' => 0],
            'tooltipText' => 'Sesiones 100% en vivo, si no puedes asistir, puedes revisar posteriormente la grabacion en tu aula virtual.',
        ],
        [
            'id' => 'tea-deteccion-temprana',
            'title' => 'Trastornos del Espectro Autista: Deteccion Temprana',
            'type' => 'Curso',
            'instructor' => 'Dr. Roberto Alarcon',
            'category' => 'psicologia-infantil',
            'startDate' => '02/06/2026',
            'originalPrice' => 350000,
            'discountPrice' => 350000,
            'modality' => 'Online',
            'image' => 'https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?w=600&h=400&fit=crop',
            'description' => 'Identifica senales tempranas del TEA y conoce los protocolos de evaluacion y derivacion.',
            'rating' => 4.8,
            'reviewCount' => 86,
            'status' => 'Proximo a iniciar',
            'discountEndsIn' => ['days' => 0, 'hours' => 0, 'minutes' => 0, 'seconds' => 0],
            'tooltipText' => 'Curso 100% online con material disponible en tu aula virtual por 8 semanas.',
        ],
        [
            'id' => 'terapia-pareja-sistemica',
            'title' => 'Terapia de Pareja con Enfoque Sistemico',
            'type' => 'Acreditacion',
            'instructor' => 'Dra. Alejandra Herrera',
            'category' => 'terapia-de-pareja',
            'startDate' => '08/06/2026',
            'originalPrice' => 420000,
            'discountPrice' => 420000,
            'modality' => 'Presencial',
            'image' => 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&h=400&fit=crop',
            'description' => 'Domina el enfoque sistemico aplicado a la terapia de pareja con herramientas practicas.',
            'rating' => 4.7,
            'reviewCount' => 58,
            'status' => 'En progreso',
            'discountEndsIn' => ['days' => 0, 'hours' => 0, 'minutes' => 0, 'seconds' => 0],
            'tooltipText' => 'Sesiones presenciales en sede Santiago. Incluye material de apoyo digital.',
        ],
        [
            'id' => 'gestion-conflictos-parejas',
            'title' => 'Gestion de Conflictos y Comunicacion en Parejas',
            'type' => 'Curso',
            'instructor' => 'Dr. Matias Espinoza',
            'category' => 'terapia-de-pareja',
            'startDate' => '15/06/2026',
            'originalPrice' => 300000,
            'discountPrice' => 239990,
            'modality' => 'En Vivo',
            'image' => 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&h=400&fit=crop',
            'description' => 'Estrategias basadas en evidencia para la resolucion de conflictos y mejora de la comunicacion.',
            'rating' => 4.5,
            'reviewCount' => 41,
            'status' => 'En progreso',
            'discountEndsIn' => ['days' => 3, 'hours' => 9, 'minutes' => 5, 'seconds' => 0],
            'tooltipText' => 'Sesiones 100% en vivo, si no puedes asistir, puedes revisar posteriormente la grabacion en tu aula virtual.',
        ],
    ],
];
